config:
    required: true

database:
    +:
        name: default
        namespace: Creonit\SearchBundle\Model
        defaultIdMethod: native

    +vendor:
        type: mysql
        parameters:
            Engine: InnoDB
            Charset: utf8

    +behavior:
        - auto_add_pk

    search_query:
        user_id: - int > user.id(setnull)
        text: text
        +behavior:
            - timestampable

    search_wordform:
        source: text
        target: text

    search_example:
        text: text